### PR TITLE
Art stuff

### PR DESCRIPTION
**Pull request by FrenzyExists**
I added a banner using figma, also added NvimTreesitter support and pandoc support

### CODE REVIEW

**Comment by MCotocel** [comment]
Can you replace this version of the banner with the other version you sent on Discord?

**Comment by FrenzyExists** [comment]
You mean the Ghost version?

**Comment by FrenzyExists** [comment]
Component 2

As in this version right?

**Comment by MCotocel** [comment]
Yep, that version

**Comment by FrenzyExists** [comment]
Noted, btw sry for the late response, college, anyway gonna do the changes real quick :+1:

**Comment by MCotocel** [comment]
Perfect, thanks!

**Pull request merged**
